### ISSUE TITLE
Using default credentials with a flow

### ISSUE THREAD

**Issue by CarlCamit** [GoogleCloudPlatform/google-auth-library-python-oauthlib#29]
Hi,

I want to be able to use the default credentials in my app engine environment to initiate a login flow.

Currently I use `flow = google_auth_oauthlib.flow.Flow.from_client_secrets_file(self.key_path, scopes=['https://www.googleapis.com/auth/spreadsheets'])`

But I don't want to have to include a service_account.json with my application.

Is it possible to use `google.auth.default()` credentials with a flow?

Thanks

**Comment by theacodes** [comment]
It's not, nor is it planned to.

**Comment by wescpy** [comment]
There is some confusion with your question. APIs accessing data owned by human users use OAuth client IDs, meaning those owners must grant your code permission to access _their_ data. Service accounts are an alternative authentication mechanism primarily involving data in the cloud, meaning owned by an application or GCP project, rather than a human. In those circumstances, you wouldn't ever need (to use) an OAuth flow because you're not seeking permission from a human user. (Instead, you will create a public/private key-pair for the service account which should have the permissions required and point your ADC/application default credentials to it. If your app is running on any GCP compute services [App Engine, Cloud Functions, Cloud Run, Compute Engine, or GKE], you can just use the [default service account](https://cloud.google.com/appengine/docs/standard/python3/service-account), easier & more convenient [for prototyping] but less secure than a user-managed service account [for production].)

That said, there are some APIs which you can use either to create valid credentials with which to access the data, again, OAuth client ID if you're seeking explicit permission from a human owner, or a service account if that service account has been granted access to that data already. The primary examples of this are Google Workspace (formerly G Suite, Google Apps) APIs. For example, you can implement OAuth client IDs and ask the owner of a Google Sheets spreadsheet to give your code permission to read from it, OR the owner can share that Sheets file with a service account.

An intermediate sample Python app that calls the Google Drive, Cloud Storage, Cloud Vision, and Google Sheets API fully using OAuth client IDs for authentication (and authorization) is described in [this post](http://goo.gle/3nPxmlc). It links to its GH repo linking to a codelab where you can build the app line-by-line, but more importantly, there is an `alt` folder that show alternative versions of the final app using service accounts and/or GCP client libraries vs. the standard Google APIs client libraries. NOTE: this is a command-line app, not a web app (yet) — I hope to eventually port it to [the GCP serverless platforms](https://cloud.google.com/serverless) (App Engine, Cloud Functions, Cloud Run) at some point.
